### ISSUE TITLE
ctrl w

### ISSUE THREAD

**Issue by majorsopa** [ballsballsballsballsballsballsballsball/game#1]
ctrl w when going slow closes tab please fix tghis ios my favote hgame every oklease

**Comment by ballsballsballsballsballsballsballsball** [comment]
This only happen in web.. how I prevent??

**Comment by majorsopa** [comment]
make the controls arrow instead maybe?

**Comment by ballsballsballsballsballsballsballsball** [comment]
OKAY

**Comment by ballsballsballsballsballsballsballsball** [comment]
https://github.com/ballsballsballsballsballsballsballsball/game/commit/4b7eb1ece7fc694797cbbd5405a92e5b3dc6c2f0
